[package]
name = "quantum-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
quantum-core = { path = "../../core" }
serde.workspace = true
serde_json.workspace = true
